FROM fedora:37

RUN dnf update -y && dnf install -y which curl cronie cronie-anacron

ENV CI=true

RUN curl -o- https://raw.githubusercontent.com/zcorky/zmicro/master/install | bash

WORKDIR /usr/local/lib/zmicro/plugins/core-utils

COPY . .

RUN zmicro info

RUN zmicro test core

