FROM debian:10.0

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y curl

ENV CI=true

RUN curl -o- https://raw.githubusercontent.com/zcorky/zmicro/master/install | bash

WORKDIR /usr/local/lib/zmicro/plugins/core-utils

COPY . .

RUN zmicro info

RUN zmicro test core
