FROM alpine:3.16

RUN apk update && apk add curl bash

ENV CI=true

RUN curl -o- https://raw.githubusercontent.com/zcorky/zmicro/master/install | bash

WORKDIR /usr/local/lib/zmicro/plugins/core-utils

COPY . .

RUN zmicro info

RUN zmicro test core
