FROM centos:centos8

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

RUN yum update -y && yum install -y curl

ENV CI=true

RUN curl -o- https://raw.githubusercontent.com/zcorky/zmicro/master/install | bash

WORKDIR /usr/local/lib/zmicro/plugins/core-utils

COPY . .

RUN zmicro info

RUN zmicro test core
