FROM archlinux:latest

RUN pacman -Sy && pacman -Syu --noconfirm curl cron

ENV CI=true

RUN curl -o- https://raw.githubusercontent.com/zcorky/zmicro/master/install | bash

WORKDIR /usr/local/lib/zmicro/plugins/core-utils

COPY . .

RUN zmicro info

RUN zmicro test core
