#!/bin/bash

function test_git::commit_message() {
  local expected=$(git log -1 --pretty=%B -n 1 | sed -e 's/ /_/g' | sed -e 's/(/_/g' | sed -e 's/)/_/g')
  local received=$(git::commit_message | sed -e 's/ /_/g' | sed -e 's/(/_/g' | sed -e 's/)/_/g')

  testing::expect \
    "${FUNCNAME[0]}" \
    "to_equal" \
    "$expected" \
    "$received"
}

function test_git::commit_message_full() {
  local expected=$(git log -1 --pretty=%B | sed -e 's/ /_/g' | sed -e 's/(/_/g' | sed -e 's/)/_/g')
  local received=$(git::commit_message_full | sed -e 's/ /_/g' | sed -e 's/(/_/g' | sed -e 's/)/_/g')

  testing::expect \
    "${FUNCNAME[0]}" \
    "to_equal" \
    "$expected" \
    "$received"
}

function test_git::commit_hash() {
  local expected=$(git rev-parse --short=9 HEAD)
  local received=$(git::commit_hash)

  testing::expect \
    "${FUNCNAME[0]}" \
    "to_equal" \
    "$expected" \
    "$received"
}

function test_git::commit_author() {
  local expected=$(git show -s --format='%ae')
  local received=$(git::commit_author)

  testing::expect \
    "${FUNCNAME[0]}" \
    "to_equal" \
    "$expected" \
    "$received"
}

function test_git::commit_timestamp() {
  local expected=$(git show -s --format=%cd --date="format:%Y-%m-%d")
  local received=$(git::commit_timestamp)

  testing::expect \
    "${FUNCNAME[0]}" \
    "to_equal" \
    "$expected" \
    "$received"
}

function test_git::commit_timestamp_date() {
  local expected=$(git show -s --format=%cd --date="format:%Y-%m-%d")
  local received=$(git::commit_timestamp_date)

  testing::expect \
    "${FUNCNAME[0]}" \
    "to_equal" \
    "$expected" \
    "$received"
}

function test_git::commit_timestamp_ms() {
  local expected=$(git show -s --format=%cd --date="format:%s")
  local received=$(git::commit_timestamp_ms)

  testing::expect \
    "${FUNCNAME[0]}" \
    "to_equal" \
    "$expected" \
    "$received"
}

function test_git::commit_timestamp_human() {
  local expected=$(git show -s --format=%cd | sed -e 's/ /_/g' | sed -e 's/(/_/g' | sed -e 's/)/_/g')
  local received=$(git::commit_timestamp_human | sed -e 's/ /_/g' | sed -e 's/(/_/g' | sed -e 's/)/_/g')

  testing::expect \
    "${FUNCNAME[0]}" \
    "to_equal" \
    "$expected" \
    "$received"
}

function test_git::namespace() {
  local expected="zmicro-design"
  local received=$(git::namespace)

  testing::expect \
    "${FUNCNAME[0]}" \
    "to_equal" \
    "$expected" \
    "$received"
}

function test_git::basename() {
  local expected="plugin-core-utils"
  local received=$(git::basename)

  testing::expect \
    "${FUNCNAME[0]}" \
    "to_equal" \
    "$expected" \
    "$received"
}

function test_git::origin_url() {
  local expected="https://github.com/zmicro-design/plugin-core-utils"
  local received=$(git::origin_url)

  testing::expect \
    "${FUNCNAME[0]}" \
    "to_equal" \
    "$expected" \
    "$received"
}

function test_git::repo_name() {
  local expected="zmicro-design/plugin-core-utils"
  local received=$(git::repo_name)

  testing::expect \
    "${FUNCNAME[0]}" \
    "to_equal" \
    "$expected" \
    "$received"
}

function test_git::branch() {
  local expected="$(git rev-parse --abbrev-ref HEAD)"
  local received=$(git::branch)

  testing::expect \
    "${FUNCNAME[0]}" \
    "to_equal" \
    "$expected" \
    "$received"
}
