#!/bin/bash

login::docker() {
  local username=$1
  local password=$2
  local registry=$3

  # compitable format: registry username password
  if [ "${username#http}" != "$username" ] || [ "${username#https}" != "$username" ]; then
    registry=$1
    username=$2
    password=$3
  fi

  if [ "$username" = "" ]; then
    log::error "[login::docker] username is required"
    return 1
  fi

  if [ "$password" = "" ]; then
    log::error "[login::docker] password is required"
    return 1
  fi

  log::info "[login::docker] logining to docker registry ..."
  docker login $registry -u $username -p $password >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    log::error "[login::docker] failed to login docker registry(registry: ${registry:-'Docker Hub'})."
    return 1
  fi

  log::success "[login::docker] succeed to login docker registry(registry: ${registry:-'Docker Hub'})."
}

login::npm() {
  local registry=$1
  local username=$2
  local password=$3
  local email=$4

  if [ "$registry" = "" ]; then
    log::error "[login::npm] registry is required"
    return 1
  fi

  if [ "$username" = "" ]; then
    log::error "[login::npm] username is required"
    return 1
  fi

  if [ "$password" = "" ]; then
    log::error "[login::npm] password is required"
    return 1
  fi

  if [ "$email" = "" ]; then
    log::error "[login::npm] email is required"
    return 1
  fi

  npm whoami --registry $registry >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    # auto input by-pass user interfactions in shell script
    # stackoverflow: https://superuser.com/questions/380155/how-to-by-pass-user-interactions-in-a-script
    (
      echo $username
      echo $password
      echo $email
    ) | npm login --registry $registry >>/dev/null 2>&1
  fi

  log::success "NPM Login Success"
}

login::git() {
  local registry=$1
  local username=$2
  local password=$3
  local git_credentials_path=$4

  if [ -z "$git_credentials_path" ]; then
    git_credentials_path=$HOME/.git-credentials
  fi

  local protocol=https

  if [ "$registry" = "" ]; then
    log::error "[login::git] registry is required"
    return 1
  fi

  if [ "$(string::match $registry ^http)" = "true" ]; then
    if [ "${registry:0:5}" = "http:" ]; then
      protocol=http
    fi

    registry=$(string::replace $registry "http://" "")
    registry=$(string::replace $registry "https://" "")
  fi

  if [ "$username" = "" ]; then
    log::error "[login::git] username is required"
    return 1
  fi

  if [ "$password" = "" ]; then
    log::error "[login::git] password is required"
    return 1
  fi

  # not safe
  git config --global credential.helper store

  # use cache instead of store for safe
  # git config --global credential.helper 'cache --timeout=604800'

  local credential=$protocol://$username:$password@$registry

  if [ -f "$git_credentials_path" ]; then
    cat $git_credentials_path | grep "$credential" >>/dev/null 2>&1
    if [ "$?" = "0" ]; then
      # found credential
      # log::success "ignore"
      return
    fi
  fi

  echo $credential | fs::append $git_credentials_path
}

export -f login::docker
export -f login::npm
export -f login::git

