#!/bin/bash

pm() {
  # MacOS
  if [ "$(os::is_macos)" = "true" ]; then
    if [ "$(os::has_command brew)" != "true" ]; then
      log::info "[$(timestamp)] homebrew is not installed, installing ..."
      zmicro package install brew
    fi

    # ignore -yqq in mac
    local args=""
    for arg in $@; do
      case $arg in
      -yqq) ;;
      -y) ;;
      *)
        args="$args $arg"
        ;;
      esac
    done

    brew $args
    return
  fi

  # CentOS
  if [ "$(os::has_command yum)" = "true" ]; then
    sudo yum $@
    return
  fi

  # Ubuntu/Debian
  if [ "$(os::has_command apt)" = "true" ]; then
    sudo apt $@
    return
  fi

  # Alpine
  if [ "$(os::has_command apk)" = "true" ]; then
    local args=""
    for arg in $@; do
      case $arg in
      install)
        args="$args add"
        ;;
      *)
        args="$args $arg"
        ;;
      esac
    done

    sudo apk $args
    return
  fi

  # Fedora
  if [ "$(os::has_command dnf)" = "true" ]; then
    sudo dnf $@
    return
  fi

  # Archlinux
  if [ "$(os::has_command pacman)" = "true" ]; then
    # ignore -yqq in mac
    local args=""
    for arg in $@; do
      case $arg in
      -yqq) ;;
      -y) ;;
      install)
        args="$args -Syu --noconfirm"
        ;;
      *)
        args="$args $arg"
        ;;
      esac
    done

    sudo pacman $args
    return
  fi

  # Flatpak
  if [ "$(os::has_command flatpak)" = "true" ]; then
    # ignore -yqq in mac
    local args=""
    for arg in $@; do
      case $arg in
      -yqq) ;;
      -y) ;;
      *)
        args="$args $arg"
        ;;
      esac
    done

    sudo flatpak $args
    return
  fi

  # Scoop
  if [ "$(os::has_command scoop)" = "true" ]; then
    # ignore -yqq in mac
    local args=""
    for arg in $@; do
      case $arg in
      -yqq) ;;
      -y) ;;
      *)
        args="$args $arg"
        ;;
      esac
    done

    sudo scoop $args
    return
  fi

  # Winget
  if [ "$(os::has_command winget)" = "true" ]; then
    # ignore -yqq in mac
    local args=""
    for arg in $@; do
      case $arg in
      -yqq) ;;
      -y) ;;
      *)
        args="$args $arg"
        ;;
      esac
    done

    sudo winget $args
    return
  fi

  log::error "[pm] unknown system package manager"
  exit 1
}

# node npm
pm::npm() {
  # ZMICRO_NVM
  if [ -z "$NODE_HOME" ]; then
    export NODE_HOME=/usr/local/node
    export NODE_USER_HOME=$HOME/.node
    export PATH=$NODE_USER_HOME/bin:$NODE_HOME/bin:$PATH
  fi

  if [ "$(os::is_nodejs_installed)" = "false" ]; then
    zpackage install nodejs
  fi

  # @TODO
  if [ "$(net::is_google_visitable)" = "false" ]; then
    export NPM_CONFIG_REGISTRY=https://registry.npmmirror.com
  fi

  npm $@
}

export -f pm
export -f pm::npm
