#!/bin/bash

pm() {
  # MacOS
  if [ "$(os::is_macos)" = "true" ]; then
    which brew >>/dev/null 2>&1
    if [ "$?" != "0" ]; then
      log::info "[$(timestamp)] homebrew is not installed, installing ..."
      zmicro package install brew
    fi

    # ignore -yqq in mac
    local args=""
    for arg in $@; do
      case $arg in
      -yqq) ;;
      -y) ;;
      *)
        args="$args $arg"
        ;;
      esac
    done

    brew $args
    return
  fi

  # CentOS
  which yum >>/dev/null 2>&1
  if [ "$?" = "0" ]; then
    sudo yum $@
    return
  fi

  # Ubuntu/Debian
  which apt >>/dev/null 2>&1
  if [ "$?" = "0" ]; then
    sudo apt $@
    return
  fi

  # Alpine
  which apk >>/dev/null 2>&1
  if [ "$?" = "0" ]; then
    sudo apk $@
    return
  fi

  # Fedora
  which dnf >>/dev/null 2>&1
  if [ "$?" = "0" ]; then
    sudo dnf $@
    return
  fi

  # Archlinux
  which pacman >>/dev/null 2>&1
  if [ "$?" = "0" ]; then
    # ignore -yqq in mac
    local args=""
    for arg in $@; do
      case $arg in
      -yqq) ;;
      -y) ;;
      install)
        args="$args -Syu"
        ;;
      *)
        args="$args $arg"
        ;;
      esac
    done

    sudo pacman $args
    return
  fi

  # Flatpak
  which flatpak >>/dev/null 2>&1
  if [ "$?" = "0" ]; then
    # ignore -yqq in mac
    local args=""
    for arg in $@; do
      case $arg in
      -yqq) ;;
      -y) ;;
      *)
        args="$args $arg"
        ;;
      esac
    done

    sudo flatpak $args
    return
  fi

  # Scoop
  which scoop >>/dev/null 2>&1
  if [ "$?" = "0" ]; then
    # ignore -yqq in mac
    local args=""
    for arg in $@; do
      case $arg in
      -yqq) ;;
      -y) ;;
      *)
        args="$args $arg"
        ;;
      esac
    done

    sudo scoop $args
    return
  fi

  # Winget
  which winget >>/dev/null 2>&1
  if [ "$?" = "0" ]; then
    # ignore -yqq in mac
    local args=""
    for arg in $@; do
      case $arg in
      -yqq) ;;
      -y) ;;
      *)
        args="$args $arg"
        ;;
      esac
    done

    sudo winget $args
    return
  fi

  log::error "[pm] unknown system package manager"
  exit 1
}

# node npm
pm::npm() {
  # ZMICRO_NVM
  if [ -z "$NODE_HOME" ]; then
    export NODE_HOME=/usr/local/node
    export NODE_USER_HOME=$HOME/.node
    export PATH=$NODE_USER_HOME/bin:$NODE_HOME/bin:$PATH
  fi

  if [ "$(os::is_nodejs_installed)" = "false" ]; then
    zpackage install nodejs
  fi

  # @TODO
  if [ "$(net::is_google_visitable)" = "false" ]; then
    export NPM_CONFIG_REGISTRY=https://registry.npmmirror.com
  fi

  npm $@
}

export -f pm
export -f pm::npm
