#!/bin/bash

users::all() {
  local _users=""
  local _base_dir=""
  if [ "$(os::is_macos)" = "true" ]; then
    # echo "-"
    _base_dir="/Users"
    _users=$(ls $_base_dir)
  elif [ "$(os::is_linux)" = "true" ]; then
    # echo "-"
    _base_dir="/home"
    _users=$(ls $_base_dir)
  fi

  local users="root"
  for _user in $_users; do
    if [ "$_user" = "Shared" ]; then
      continue
    fi

    if [ "$_user" = "Guest" ]; then
      continue
    fi

    if [ -d "$_base_dir/$_user" ]; then
      users="$users $_user"
      continue
    fi
  done

  echo $users
}

users::online() {
  who
}

users::login::histories() {
  if [ ! -f "/var/log/wtmp" ]; then
    # pm install -y hostname >>/dev/null 2>&1
    return
  fi

  last
}

users::doing() {
  if [ "$(os::has_command w)" = "false" ]; then
    # pm install -y hostname >>/dev/null 2>&1
    return
  fi

  w
}

export -f users::all
export -f users::online
export -f users::login::histories
export -f users::doing
