#!/bin/bash

users::all() {
  if [ "$(os::is_macos)" = "true" ]; then
    # echo "-"
    ls /Users/
    return
  fi

  ls /home
}

users::online() {
  who
}

users::login::histories() {
  if [ ! -f "/var/log/wtmp" ]; then
    # pm install -y hostname >>/dev/null 2>&1
    return
  fi

  last
}

users::doing() {
  if [ "$(os::has_command w)" = "false" ]; then
    # pm install -y hostname >>/dev/null 2>&1
    return
  fi

  w
}

export -f users::all
export -f users::online
export -f users::login::histories
export -f users::doing
