#!/bin/bash

# var::set sets value of key
# var::set@usage <key> <value>
# var::set@example version v1.0.0
var::set() {
  local key=$1
  local value=$2

  eval "$key=$value"
}

# var::get gets value of key
# var::get@usage <key>
# var::get@example version
var::get() {
  local key=$1

  # eval "echo \${$key}"
  echo ${!key}
}

export -f var::set
export -f var::get
