#!/bin/bash

version::update() {
  PREV=$ZMICRO_VERSION

  config::load_core_mod

  LATEST=$ZMICRO_VERSION

  # echo "Load Version: $ZMICRO_VERSION"
  # echo "BBB: $PREV => $LATEST"
  log::version $PREV $LATEST

  echo $LATEST
}

version::timestamp() {
  local path=$1
  cd $path

  git::commit_timestamp
}

version::get() {
  local path=$1/mod

  local version=$(config::get VERSION $path)
  if [ -n "$version" ]; then
    echo $version
    return
  fi

  # OLD PLUGINS
  config::get PLUGIN_VERSION $path
}

version::git_hash() {
  local path=$1
  cd $path

  git::commit_hash
}

version::echo() {
  local path=$1
  local version=$(version::get $path)
  local git_hash=$(version::git_hash $path)
  local timestamp=$(version::timestamp $path)

  echo "$(color::green $version) (${git_hash} ${timestamp})"
}

version::zmicro() {
  version::get $ZMICRO_HOME
}

version::zmicro_num() {
  version::get $ZMICRO_HOME | awk -F 'v' '{print $2}'
}

version::zmicro_detail() {
  local path=$ZMICRO_HOME
  local version=$(version::get $path)
  local git_hash=$(version::git_hash $path)
  local timestamp=$(version::timestamp $path)

  echo "$version (${git_hash} ${timestamp})"
}

version::main() {
  version::echo $ZMICRO_HOME
}

version::plugin() {
  local name=$1
  if [ -z "$name" ]; then
    log::error "[$(timestamp)][version::plugin] plugin name is required"
    exit 1
  fi

  local path=$(plugin::get_path $name)
  version::echo $path
}

version::package() {
  local name=$1
  if [ -z "$name" ]; then
    log::error "[$(timestamp)][version::package] package name is required"
    exit 1
  fi

  local path=$ZMICRO_HOME/plugins/package/packages/$name
  if [ ! -d "$path" ]; then
    log::error "[$(timestamp)][version::package] package(${name}) does not exist"
    exit 1
  fi

  version::echo $path
}

version::service() {
  local name=$1
  if [ -z "$name" ]; then
    log::error "[$(timestamp)][version::service] service name is required"
    exit 1
  fi

  local path=$ZMICRO_HOME/plugins/service/services/$name
  if [ ! -d "$path" ]; then
    log::error "[$(timestamp)][version::service] service(${name}) does not exist"
    exit 1
  fi

  version::echo $path
}

version::swarm() {
  local name=$1
  if [ -z "$name" ]; then
    log::error "[$(timestamp)][version::swarm] swarm name is required"
    exit 1
  fi

  local path=$ZMICRO_HOME/plugins/swarm/swarms/$name
  if [ ! -d "$path" ]; then
    log::error "[$(timestamp)][version::swarm] swarm(${name}) does not exist"
    exit 1
  fi

  version::echo $path
}

version::at() {
  local name=$1
  if [ -z "$name" ]; then
    log::error "[$(timestamp)][version::at] at name is required"
    exit 1
  fi

  string::has @ $name
}

# Found name
# Example:
#   name@version => name
version::at_name() {
  local name=$1
  if [ -z "$name" ]; then
    log::error "[$(timestamp)][version::at_name] at name is required"
    exit 1
  fi

  echo $name | awk -F '@' '{print $1}'
}

# Found version
# Example:
#   name@version => version
version::at_version() {
  local name=$1
  if [ -z "$name" ]; then
    log::error "[$(timestamp)][version::at_version] at name is required"
    exit 1
  fi

  echo $name | awk -F '@' '{print $2}'
}

version::is_valid() {
  semver::is_valid "$@"
}

version::compare_equals() {
  semver::compare_equals "$@"
}

version::compare_gt() {
  semver::compare_gt "$@"
}

version::compare_lt() {
  semver::compare_lt "$@"
}

version::next() {
  semver::next "$@"
}

version::get_major() {
  semver::get_major "$@"
}

version::get_minor() {
  semver::get_minor "$@"
}

version::get_patch() {
  semver::get_patch "$@"
}

version::curl() {
  local name="curl"
  if [ "$(os::has_command $name)" != "true" ]; then
    echo "-"
    return
  fi

  curl --version 2>/dev/null | head -n 1
}

version::wget() {
  local name="wget"
  if [ "$(os::has_command $name)" != "true" ]; then
    echo "-"
    return
  fi

  wget --version 2>/dev/null | head -n 1
}

version::git() {
  local name="git"
  if [ "$(os::has_command $name)" != "true" ]; then
    echo "-"
    return
  fi

  git --version 2>/dev/null
}

version::code() {
  local name="code"
  if [ "$(os::has_command $name)" != "true" ]; then
    echo "-"
    return
  fi

  code --version 2>/dev/null | head -n 1
}

version::ssh() {
  local name="ssh"
  if [ "$(os::has_command $name)" != "true" ]; then
    echo "-"
    return
  fi

  ssh -V 2>&1
}

version::docker() {
  local name="docker"
  if [ "$(os::has_command $name)" != "true" ]; then
    echo "-"
    return
  fi

  docker --version 2>/dev/null | head -n 1
}

version::lima() {
  local name="lima"
  if [ "$(os::has_command $name)" != "true" ]; then
    echo "-"
    return
  fi

  lima --version 2>/dev/null | head -n 1
}

version::colima() {
  local name="colima"
  if [ "$(os::has_command $name)" != "true" ]; then
    echo "-"
    return
  fi

  colima version 2>/dev/null | head -n 1
}

version::multipass() {
  local name="multipass"
  if [ "$(os::has_command $name)" != "true" ]; then
    echo "-"
    return
  fi

  multipass version 2>/dev/null | awk -v d=" - " '{s=(NR==1?s:s d)$0}END{print s}'
}

version::node() {
  local name="node"
  if [ "$(os::has_command $name)" != "true" ]; then
    echo "-"
    return
  fi

  node --version 2>/dev/null
}

version::go() {
  local name="go"
  if [ "$(os::has_command $name)" != "true" ]; then
    echo "-"
    return
  fi

  go version 2>/dev/null
}

version::python() {
  local name="python3"
  if [ "$(os::has_command $name)" != "true" ]; then
    echo "-"
    return
  fi

  python3 --version 2>/dev/null
}

version::deno() {
  local name="deno"
  if [ "$(os::has_command $name)" != "true" ]; then
    echo "-"
    return
  fi

  deno --version 2>/dev/null | awk -v d=" - " '{s=(NR==1?s:s d)$0}END{print s}'
}

version::rust() {
  local name="rustc"
  if [ "$(os::has_command $name)" != "true" ]; then
    echo "-"
    return
  fi

  rustc --version 2>/dev/null
}

version::java() {
  local name="java"
  if [ "$(os::has_command $name)" != "true" ]; then
    echo "-"
    return
  fi

  java -version 2>&1 | head -n 2 | awk -v d=" - " '{s=(NR==1?s:s d)$0}END{print s}'
}

version::gzcaas() {
  local name="gzcaas"
  if [ "$(os::has_command $name)" != "true" ]; then
    echo "-"
    return
  fi

  gzcaas --version 2>/dev/null
}

export -f version::get
export -f version::git_hash
export -f version::timestamp

export -f version::zmicro
export -f version::zmicro_num
export -f version::zmicro_detail

export -f version::echo

export -f version::main
export -f version::plugin
export -f version::service
export -f version::swarm

export -f version::update

export -f version::at
export -f version::at_name
export -f version::at_version

export -f version::is_valid

export -f version::compare_equals
export -f version::compare_gt
export -f version::compare_lt

export -f version::next

export -f version::get_major
export -f version::get_minor
export -f version::get_patch

export -f version::curl
export -f version::wget
export -f version::git

export -f version::code
export -f version::ssh

export -f version::docker

export -f version::lima
export -f version::colima
export -f version::multipass

export -f version::node
export -f version::go
export -f version::python
export -f version::deno
export -f version::rust
export -f version::java

export -f version::gzcaas
